### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by in3otd** [PTDreamer/openMSA#1]
I'm trying to compile the SW, using Qt version 5.9.6; after working around the missing `QRandomGenerator()` in this Qt version, I get these errors:
```
calparser.cpp: In member function 'QList<calParser::magPhaseCalData_> calParser::loadMagPhaseCalDataFromFile(QString, bool&, QString&)':
calparser.cpp:206:27: error: no match for 'operator[]' (operand types are 'QJsonValue' and 'const char [13]')
   data.calFrequency = path["CalFrequency"].toDouble();
                           ^
calparser.cpp:207:22: error: no match for 'operator[]' (operand types are 'QJsonValue' and 'const char [8]')
   data.calDate = path["CalDate"].toString();
                      ^
calparser.cpp:208:23: error: no match for 'operator[]' (operand types are 'QJsonValue' and 'const char [9]')
   data.pathName = path["PathName"].toString();
                       ^
calparser.cpp:209:29: error: no match for 'operator[]' (operand types are 'QJsonValue' and 'const char [21]')
   data.centerFreq_MHZ = path["FinalFilterFrequency"].toDouble();
                             ^
calparser.cpp:210:28: error: no match for 'operator[]' (operand types are 'QJsonValue' and 'const char [21]')
   data.bandwidth_MHZ = path["FinalFilterBandwidth"].toDouble();
                            ^
calparser.cpp:211:25: error: no match for 'operator[]' (operand types are 'QJsonValue' and 'const char [11]')
   data.controlPin = path["ControlPin"].toInt();
                         ^
calparser.cpp:212:27: error: no match for 'operator[]' (operand types are 'QJsonValue' and 'const char [9]')
   QJsonArray values = path["MagTable"].toArray();
```

**Comment by in3otd** [comment]
I see that [`QJsonValue::operator[]`](https://doc.qt.io/qt-5/qjsonvalue.html#operator-5b-5d) was introduced in Qt 5.10, so probably there is no easy way to use 5.9...
Qt 5.10 seems relatively new, Ubuntu 18.04.2, the latest LTS, has 5.9.5 and I think also other distros are not shipping with Qt 5.10. It would be good if also 5.9 was supported, IMHO.
Upgrading Qt in Ubuntu 18.04.2 may not be straightforward, see https://unix.stackexchange.com/questions/481063/ubuntu-18-04-1-lts-x64-how-to-update-qt-5-10-from-qt-5-9-5 (but I did not try).
I've spent some time to setup [Travis](https://docs.travis-ci.com/user/reference/overview/) to compile this project and the latest Ubuntu distro it has is 18.04 so cannot go further without fixing this.

**Comment by PTDreamer** [comment]
I have looked into this last night. Supporting  earlier versions of Qt would require a lot of refactoring, and worse, it would eventually break when distros finally update their shipped qt since there were a lot of non retro compatible changes to the framework. Installing QT from qt.io even on headless systems is very straightforward so atm I'm inclined to mark this as 'won't fix'.

**Comment by PTDreamer** [comment]
Just for the record I'm currently using 5.12.2.
Install manager from qt.io allows the choice of which framework version/s to install.

**Comment by in3otd** [comment]
yep, I understand it can be quite some work to support earlier Qt releases. I'm certainly not an expert on Qt stuff, my hope was that it was possible to make the SW work on Qt 5.9 since this seems the most widely available.
Then, I'm coming from the Slackware world, which at present ships only with Qt 4.7 and has an optional user-provided package for Qt 5.9 :grin: .
I guess I may wait until Qt 5.10 is more widely available; nevertheless, could you please list the steps you followed to install the latest Qt from qt.io? I may try that in Travis; I think it would be useful to enable it here. BTW, there I had to fix a couple of small stuff there, e.g. having to `#include <cmath>` and use `std::round()` instead of `round()`, etc.

**Comment by PTDreamer** [comment]
> could you please list the steps you followed to install the latest Qt from qt.io?

Give me a couple of days I'll install a new VM and start from prestine Ubuntu. I'll work on both desktop and headless walktroughs.

**Comment by PTDreamer** [comment]
Hi I have added two wiki pages, one for Ubuntu desktop build procedure, and one for Ubuntu server
[wiki link](https://github.com/PTDreamer/openMSA/wiki)

About travis configuration you can also have a look here https://github.com/skalee/non-interactive-qt-installer

**Comment by in3otd** [comment]
thanks - I saw you also made good progress with Travis.

**Comment by PTDreamer** [comment]
Yes, thank you for letting me know travis is free. Linux builds and packaging is working for both projects, I'm working on windows now.
